  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: mysql
    namespace: insult
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: nutanix-volume