apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: insultgenerator-app-qa
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/techjw/demo-gitops-quarkus.git'
    path: k8s/environments/qa
    targetRevision: demo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
